[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "n8n"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.envs]
N8N_BASIC_AUTH_ACTIVE = "true"
N8N_BASIC_AUTH_USER = "admin"
N8N_USER_MANAGEMENT_DISABLED = "false"
N8N_DIAGNOSTICS_ENABLED = "false"
N8N_RUNNERS_ENABLED = "true"
GENERIC_TIMEZONE = "UTC"
DB_TYPE = "postgresdb"
DB_POSTGRESDB_PORT = "5432"
DB_POSTGRESDB_DATABASE = "n8n"
DB_POSTGRESDB_USER = "n8n" 