# Use the official n8n Docker image
FROM n8nio/n8n:latest

# Set environment variables
ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_BASIC_AUTH_USER=admin
ENV N8N_BASIC_AUTH_PASSWORD=${N8N_PASSWORD:-changeme}
ENV N8N_HOST=${N8N_HOST:-localhost}
ENV N8N_PORT=5678
ENV N8N_PROTOCOL=${N8N_PROTOCOL:-http}
ENV N8N_USER_MANAGEMENT_DISABLED=false
ENV N8N_DIAGNOSTICS_ENABLED=false
ENV N8N_RUNNERS_ENABLED=true
ENV WEBHOOK_URL=${WEBHOOK_URL:-http://localhost:5678/}
ENV GENERIC_TIMEZONE=UTC

# Database configuration
ENV DB_TYPE=postgresdb
ENV DB_POSTGRESDB_HOST=${DB_POSTGRESDB_HOST:-postgres}
ENV DB_POSTGRESDB_PORT=5432
ENV DB_POSTGRESDB_DATABASE=n8n
ENV DB_POSTGRESDB_USER=n8n
ENV DB_POSTGRESDB_PASSWORD=${DB_POSTGRESDB_PASSWORD:-n8n}

# Expose port
EXPOSE 5678

# Start n8n
CMD ["n8n"] 